version: '3'

services:

  kv:
    restart: always
    container_name: art-kv
    build:
      context: ../../docker/kvrocks
      dockerfile: Dockerfile
    # mem_limit: 1G
    environment:
      KVROCKS_ARGS: |
        --requirepass ${KV_PASSWORD}
        --workers ${KV_WORKERS}
        --log /log
        --dir /data
        --timeout 360
        --rocksdb.compression zstd
        --rocksdb.enable_blob_files yes
        --rocksdb.read_options.async_io yes
    volumes:
      - ./data/kv:/data
      - ./log/kv:/log
    ports:
      - ${KV_PORT}:6666

  gt:
    container_name: art-gt
    image: greptime/greptimedb:v0.4.0-nightly-20230821
    # image: greptime/greptimedb
    ports:
      - ${GT_HTTP_PORT}:${GT_HTTP_PORT}
      - ${GT_PG_PORT}:${GT_PG_PORT}
    command: >
      standalone start -c /gt/conf.toml
    volumes:
      - ./data/gt:/data
      - ./cache/gt:/cache
      - ./gt:/gt

