version: '3'

services:

  kv:
    restart: always
    container_name: art-kv
    image: apache/kvrocks
    entrypoint: >
      kvrocks
      -c /var/lib/kvrocks/kvrocks.conf
      --bind "0.0.0.0"
      --pidfile /var/run/kvrocks/kvrocks.pid
      --requirepass ${KV_PASSWORD}
      --workers ${KV_WORKERS}
      --log /log
      --dir /data
      --timeout 360
      --rocksdb.compression zstd
      --rocksdb.enable_blob_files yes
      --rocksdb.read_options.async_io yes
      --rename-command 'FLUSHDB ""'
      --rename-command 'FLUSHALL ""'
      --rename-command 'CONFIG ""'
      --rename-command 'KEYS ""'
    volumes:
      - ./data/kv:/data
      - ./log/kv:/log
    ports:
      - ${KV_PORT}:6666

  gt:
    container_name: art-gt
    image: greptime/greptimedb:v0.4.0-nightly-20230925
    # image: greptime/greptimedb
    ports:
      - ${GT_HTTP_PORT}:${GT_HTTP_PORT}
      - ${GT_PG_PORT}:${GT_PG_PORT}
    command: >
      standalone start -c /gt/conf.toml
    volumes:
      - /tmp/backup/greptime:/tmp/backup/greptime
      - ./data/gt:/data
      - ./cache/gt:/cache
      - ./gt:/gt

